NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	correct	correct	incorrect	incorrect	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the carpet	correct	neither	incorrect	to the child	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the child	incorrect	neither	incorrect	to the carpet	correct
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the child	incorrect	to the carpet	correct
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the child	incorrect	neither	incorrect	to the carpet	correct
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the child	incorrect	neither	incorrect	to the carpet	correct
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	correct	correct	incorrect	incorrect	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the child	incorrect	neither	incorrect	to the carpet	correct
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the child	incorrect	neither	incorrect	to the carpet	correct
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the child	incorrect	to the carpet	correct
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the child	incorrect	to the carpet	correct	neither	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the child	incorrect	to the carpet	correct
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the carpet	correct	neither	incorrect	to the child	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \#%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem \\#%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	correct	correct	incorrect	incorrect	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem \#${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem \#${i}, are electrons transferred to the carpet, or to the child?	to the child	incorrect	to the carpet	correct	neither	incorrect
NUM	In problem \#${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem \${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem \#${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem \#${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	correct	correct	incorrect	incorrect	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	to the carpet	correct	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	neither	incorrect	to the carpet	correct
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	to the carpet	correct	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	neither	incorrect	to the carpet	correct
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	neither	incorrect	to the carpet	correct
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	to the carpet	correct	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	to the carpet	correct	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	correct	correct	incorrect	incorrect	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	to the carpet	correct	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the child	incorrect	to the carpet	correct
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the child	incorrect	to the carpet	correct
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the carpet	correct	neither	incorrect	to the child	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	correct	correct	incorrect	incorrect	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	correct	correct	incorrect	incorrect	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the child	incorrect	to the carpet	correct
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	to the carpet	correct	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	correct	correct	incorrect	incorrect	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	to the carpet	correct	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	neither	incorrect	to the carpet	correct
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	correct	correct	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	neither	incorrect	to the carpet	correct
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	to the child	incorrect	to the carpet	correct	neither	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #%(i)s, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #%(i)s, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #%(i)s, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem #%(i)s, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #%(i)s, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #%(i)s, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem #%(i)s, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #1, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	2.23E+00	2.23E-02
NUM	In problem #1, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #1, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the carpet	correct	to the child	incorrect
NUM	In problem #3, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #10, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #10, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem #10, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #1, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	1.10E+01	1.10E-01
NUM	In problem #1, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #1, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the child	incorrect	to the carpet	correct
NUM	In problem #3, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #10, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #10, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem #10, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #${i}, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	1.10E+01	1.10E-01
NUM	In problem #${i}, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #${i}, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the child	incorrect	to the carpet	correct
NUM	In problem #${i}, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #${i}, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #${i}, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect
NUM	In problem #${i}, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	correct	correct	incorrect	incorrect	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #1, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	1.10E+01	1.10E-01
NUM	In problem #1, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #1, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the child	incorrect	to the carpet	correct
NUM	In problem #3, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #10, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #10, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem #10, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	incorrect	incorrect	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #1, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	1.36E+05	1.36E+03
NUM	In problem #1, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #1, are electrons transferred to the carpet, or to the child?	to the child	incorrect	neither	incorrect	to the carpet	correct
NUM	In problem #3, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #10, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #10, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem #10, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	correct	correct	incorrect	incorrect	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #1, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	1.36E+05	1.36E+03
NUM	In problem #1, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #1, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the child	incorrect	to the carpet	correct
NUM	In problem #3, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #10, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #10, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem #10, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #1, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	1.36E+05	1.36E+03
NUM	In problem #1, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #1, are electrons transferred to the carpet, or to the child?	neither	incorrect	to the child	incorrect	to the carpet	correct
NUM	In problem #3, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #10, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #10, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem #10, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four
TF	Is this question true/false?	false
NUM	In problem #1, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	1.36E+05	1.36E+03
NUM	In problem #1, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #1, are electrons transferred to the carpet, or to the child?	to the carpet	correct	to the child	incorrect	neither	incorrect
NUM	In problem #3, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #10, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #10, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect
NUM	In problem #10, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	incorrect	incorrect	correct	correct	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four	${misdirect}
TF	Is this question true/false?	false
NUM	In problem #1, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	1.36E+05	1.36E+03
NUM	In problem #1, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #1, are electrons transferred to the carpet, or to the child?	to the carpet	correct	neither	incorrect	to the child	incorrect
NUM	In problem #3, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #10, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #10, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect
NUM	In problem #10, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	incorrect	incorrect	incorrect	incorrect	correct	correct	correct	correct
ORD	This is a ordering question.	one	two	three	four	${misdirect}
TF	Is this question true/false?	false
NUM	In problem #1, you needed to calculate the net charge of a penny with all of its negative charge removed. What is the net charge of the penny after all the negative charge has been removed? Give your answer in Coulombs.	1.36E+05	1.36E+03
NUM	In problem #1, what was the force you calculated? Give your answer in Newtons.	4.36E+00	4.36E-02
MC	In problem #1, are electrons transferred to the carpet, or to the child?	to the child	incorrect	neither	incorrect	to the carpet	correct
NUM	In problem #3, what is the total charge you calculated? Give your answer in Coulombs.	-1.60E-13	1.00E-15
NUM	In problem #10, assume that the electron and proton are separated by 0.50 m. What is the magnitude of the electrostatic force between the proton and electron? Give your answer in Newtons.	9.23E-28	1.00E-30
MC	In problem #10, is it possible to place the electron and proton some distance appart such that the force of gravity is stronger than the electrostatic force?	Yes, if the proton and electron are separated by a very large distance, the force of gravity will be larger.	incorrect	Yes, for short and long distances the electrostaitc force is greater, for for medium ranges, the force of gravity will be larger.	incorrect	Yes, if the proton and electron are brought very close together, the force of gravity will be larger.	incorrect	No, the ratio of the magnitude of the two forces does not depend on their separation distance.	correct
NUM	In problem #10, how much charge was placed on the first sphere during the induction process? Give your answer in Coulombs.	4.72E-08	1.00E-10
MA	This is a multi-answer question.	correct	correct	correct	correct	incorrect	incorrect	incorrect	incorrect
ORD	This is a ordering question.	one	two	three	four	five
TF	Is this question true/false?	false
