NUM	1 - In problem #1, you needed to calculate the net charge of a penny	1.36E+05	1.36E+03
MA	2 - MA question, #a - b	two	incorrect	one	correct	three	correct
MC	3 - MC question	two	incorrect	three	incorrect	one	correct
ORD	4 - ORD question	first	second	third
TF	5 - TF question	true
MC	3 - MC question with link (http://scatcat.fhsu.edu/~cclark/Phys212/picture1.png)	two	incorrect	one	correct	three	incorrect
